# Generated by Django 4.2.7 on 2023-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("terminado_em", models.DateTimeField(null=True)),
            ],
        ),
    ]
